name: Tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    matrix:
      php:
        - 8.3
        - 8.4
      laravel:
        - 11
        - 12
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: highest
          composer-options: --with laravel/framework:^${{ matrix.laravel }}
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
